name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        example: [vanilla, react, vue, svelte]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Bootstrap packages
        run: npx lerna bootstrap

      - name: Build core
        run: npm run build

      - name: Start example app
        run: npm run dev:${{ matrix.example }} &
        env:
          # This ensures the process doesn't block
          BROWSER: none

      - name: Wait for server
        run: npx wait-on http://localhost:5173 --timeout 60000

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: e2e-tests
          browser: chrome
          config: baseUrl=http://localhost:5173

      - name: Upload screenshots (on failure)
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots-${{ matrix.example }}
          path: e2e-tests/cypress/screenshots

      - name: Upload videos
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos-${{ matrix.example }}
          path: e2e-tests/cypress/videos